c_compiler:
  - m2w64-toolchain          # [win]

python:
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  - 3.14.* *_cp314

is_python_min:
  - false
  - false
  - false
  - false
  - true

zip_keys:
  - python
  - is_python_min
